# containers/Dockerfile.scanpy
FROM continuumio/miniconda3:24.1.2-0

WORKDIR /app

COPY envs/env_scanpy.yaml /tmp/env_scanpy.yaml
RUN conda env create -f /tmp/env_scanpy.yaml && conda clean -afy

COPY . /app
RUN conda run -n env_scanpy pip install -e /app --no-deps

SHELL ["conda", "run", "-n", "env_scanpy", "/bin/bash", "-c"]
ENTRYPOINT ["conda", "run", "-n", "env_scanpy", "scanpy-workflow"]
